// 基于数据空间的数据服务
export interface DataSpaceDataConfig {
  [key: string]: {
    dataOfferings: any[];
    dataContracts: any[];
    connectedConnectors: any[];
    digitalContracts: any[];
    policyTemplates: any[];
    contractTemplates: any[];
    externalOfferings: any[];
    dataRequests: any[];
    blockchainNetworks: any[];
    blockchainTransactions: any[];
    auditLogs: any[];
  };
}

export const dataSpaceConfigs: DataSpaceDataConfig = {
  healthcare: {
    dataOfferings: [
      {
        id: "h1",
        title: "Patient Demographics Dataset",
        description: "Anonymized patient demographic data for healthcare analytics",
        dataType: "local_file",
        accessPolicy: "GDPR Compliant",
        status: "active",
        registrationStatus: "registered",
        createdAt: "2024-01-10T10:00:00Z",
        sourceConfig: {
          filePath: "/data/healthcare/patient_demographics.csv",
          format: "CSV",
          fileSize: "2.5 GB",
        },
      },
      {
        id: "h2", 
        title: "Medical Imaging Archive",
        description: "De-identified medical imaging data for research",
        dataType: "s3",
        accessPolicy: "Research Only",
        status: "active",
        registrationStatus: "registered",
        createdAt: "2024-01-12T14:30:00Z",
        sourceConfig: {
          bucketName: "medical-imaging-archive",
          objectKey: "dicom/research-dataset",
          region: "us-east-1",
        },
      },
    ],
    dataContracts: [
      {
        id: "hc1",
        name: "Patient Data Access Contract",
        contractAddress: "0xhealth123456789abcdef123456789abcdef123456",
        providerDID: "did:health:provider123",
        consumerDID: "did:health:consumer456",
        policy: "GDPR Compliance",
        status: "active",
        createdAt: "2024-01-10T10:00:00Z",
        expiresAt: "2024-12-31T23:59:59Z",
        accessCount: 1523,
        dataVolume: "45.2 GB",
        maxAccessCount: 5000,
        violationCount: 0,
        isViolated: false,
        isExpired: false,
      },
      {
        id: "hc2",
        name: "Medical Research Data Contract",
        contractAddress: "0xhealth987654321fedcba987654321fedcba987654",
        providerDID: "did:health:provider789",
        consumerDID: "did:health:consumer123",
        policy: "Medical Research",
        status: "in_use",
        createdAt: "2024-01-12T14:30:00Z",
        expiresAt: "2024-06-30T23:59:59Z",
        accessCount: 89,
        dataVolume: "12.7 GB",
        maxAccessCount: 1000,
        violationCount: 0,
        isViolated: false,
        isExpired: false,
      },
      {
        id: "hc3",
        name: "Expired Research Contract",
        contractAddress: "0xhealth111222333444555666777888999000aaabbb",
        providerDID: "did:health:provider999",
        consumerDID: "did:health:consumer999",
        policy: "Research Only",
        status: "expired",
        createdAt: "2023-01-15T10:00:00Z",
        expiresAt: "2024-01-15T23:59:59Z",
        accessCount: 2050,
        dataVolume: "78.3 GB",
        maxAccessCount: 2000,
        violationCount: 2,
        isViolated: true,
        isExpired: true,
      },
    ],
    connectedConnectors: [
      {
        id: "hconn1",
        name: "Hospital Network EU",
        did: "did:health:hospital-eu-123",
        status: "connected",
        lastSeen: "2024-01-15T08:30:00Z",
        offeringsCount: 15,
      },
      {
        id: "hconn2", 
        name: "Research Institute",
        did: "did:health:research-inst-456",
        status: "connected",
        lastSeen: "2024-01-14T16:45:00Z",
        offeringsCount: 8,
      },
    ],
    digitalContracts: [],
    policyTemplates: [
      {
        id: "hp1",
        name: "Access Period Limitation",
        description: "Maximum access period for patient data - 30 days",
        rules: [
          {
            id: "hr1",
            type: "access_period",
            name: "Access Period Limitation",
            description: "Maximum access period for patient data",
            value: 30,
            unit: "days",
            isActive: true,
          },
        ],
        category: "access",
        severity: "high",
        enforcementType: "automatic",
        createdAt: "2024-01-10T10:00:00Z",
      },
      {
        id: "hp2",
        name: "Access Count Limitation",
        description: "Maximum number of data access requests per month - 100 requests",
        rules: [
          {
            id: "hr2",
            type: "access_count",
            name: "Access Count Limit",
            description: "Maximum number of data access requests per month",
            value: 100,
            unit: "requests/month",
            isActive: true,
          },
        ],
        category: "usage",
        severity: "medium",
        enforcementType: "automatic",
        createdAt: "2024-01-10T11:00:00Z",
      },
      {
        id: "hp3",
        name: "Identity Restriction",
        description: "Only verified medical professionals can access",
        rules: [
          {
            id: "hr3",
            type: "identity_restriction",
            name: "Medical Professional Only",
            description: "Only verified medical professionals can access",
            value: "medical_professional",
            isActive: true,
          },
        ],
        category: "compliance",
        severity: "high",
        enforcementType: "manual",
        createdAt: "2024-01-10T12:00:00Z",
      },
      {
        id: "hp4",
        name: "Encryption & Transmission Protection",
        description: "All data must be encrypted with AES-256",
        rules: [
          {
            id: "hr4",
            type: "encryption",
            name: "End-to-End Encryption",
            description: "All data must be encrypted with AES-256",
            value: "AES-256",
            isActive: true,
          },
        ],
        category: "compliance",
        severity: "high",
        enforcementType: "automatic",
        createdAt: "2024-01-10T13:00:00Z",
      },
      {
        id: "hp5",
        name: "Access IP Restriction",
        description: "Only specified IP addresses can access healthcare data",
        rules: [
          {
            id: "hr5",
            type: "ip_restriction",
            name: "IP Whitelist",
            description: "Only specified IP addresses can access healthcare data",
            value: "192.168.100.0/24,10.20.0.0/16",
            isActive: true,
          },
        ],
        category: "access",
        severity: "medium",
        enforcementType: "automatic",
        createdAt: "2024-01-10T14:00:00Z",
      },
      {
        id: "hp6",
        name: "Single Transfer Limit",
        description: "Maximum data transfer per session - 1000 records",
        rules: [
          {
            id: "hr6",
            type: "transfer_limit",
            name: "Transfer Volume Limit",
            description: "Maximum data transfer per session",
            value: 1000,
            unit: "records",
            isActive: true,
          },
        ],
        category: "usage",
        severity: "medium",
        enforcementType: "automatic",
        createdAt: "2024-01-10T15:00:00Z",
      },
      {
        id: "hp7",
        name: "Data Transmission QPS Limit",
        description: "Maximum queries per second for healthcare APIs - 5 QPS",
        rules: [
          {
            id: "hr7",
            type: "qps_limit",
            name: "Query Rate Limit",
            description: "Maximum queries per second for healthcare APIs",
            value: 5,
            unit: "queries/second",
            isActive: true,
          },
        ],
        category: "usage",
        severity: "medium",
        enforcementType: "automatic",
        createdAt: "2024-01-10T16:00:00Z",
      },
    ],
    contractTemplates: [
      {
        id: "hc1",
        name: "Basic Healthcare Access Contract",
        description: "Basic contract with access period and encryption requirements",
        policyIds: ["hp1", "hp4"],
        policies: [],
        contractType: "multi_policy",
        status: "active",
        createdAt: "2024-01-10T10:00:00Z",
        usageCount: 15,
      },
      {
        id: "hc2",
        name: "Medical Research Contract", 
        description: "Comprehensive contract for medical research with full restrictions",
        policyIds: ["hp1", "hp2", "hp3", "hp4", "hp6"],
        policies: [],
        contractType: "multi_policy",
        status: "active",
        createdAt: "2024-01-15T09:00:00Z",
        usageCount: 8,
      },
      {
        id: "hc3",
        name: "Secure Access Contract",
        description: "High-security contract with all access controls",
        policyIds: ["hp1", "hp3", "hp4", "hp5", "hp7"],
        policies: [],
        contractType: "multi_policy",
        status: "active",
        createdAt: "2024-01-18T14:00:00Z",
        usageCount: 12,
      },
    ],
    externalOfferings: [
      {
        id: "he1",
        title: "Clinical Trial Data",
        description: "Phase III clinical trial datasets",
        dataType: "JSON/CSV",
        provider: "Pharma Research Corp",
        providerDID: "did:health:pharma123",
        accessPolicy: "Research License",
        category: "research",
        lastUpdated: "2024-01-15T08:00:00Z",
        size: "5.2 GB",
        price: "$2000/month",
      },
    ],
    dataRequests: [
      {
        id: "hdr1",
        offeringId: "he1",
        offeringTitle: "Clinical Trial Data",
        provider: "Pharma Research Corp",
        requestedAt: "2024-01-18T09:00:00Z",
        status: "approved",
        accessMode: "api",
        purpose: "Medical research for drug efficacy analysis",
      },
      {
        id: "hdr2",
        offeringId: "he2",
        offeringTitle: "Medical Imaging Archive",
        provider: "Imaging Research Center",
        requestedAt: "2024-01-19T14:30:00Z",
        status: "pending",
        accessMode: "download",
        purpose: "AI model training for diagnostic assistance",
      },
      {
        id: "hdr3",
        offeringId: "he3",
        offeringTitle: "Patient Demographics Dataset",
        provider: "Healthcare Analytics Inc",
        requestedAt: "2024-01-17T11:15:00Z",
        status: "completed",
        accessMode: "api",
        purpose: "Population health study",
      },
    ],
    blockchainNetworks: [
      {
        id: "healthcare-main",
        name: "Healthcare Identity Chain",
        type: "ZLTC",
        chainType: "main",
        chainId: 1001,
        status: "connected",
        curveAlgorithm: "Secp256k1",
        witnessNodes: 7,
        consensusNodes: 4,
        blockHeight: 2456789,
        purpose: "Identity Management",
        description: "Main chain for DID registration and identity verification in healthcare sector",
      },
      {
        id: "healthcare-sub",
        name: "Healthcare Business Chain",
        type: "ZLTC",
        chainType: "sub",
        chainId: 1002,
        status: "connected",
        curveAlgorithm: "Sm2p256v1",
        witnessNodes: 5,
        consensusNodes: 3,
        blockHeight: 1234567,
        purpose: "Business Operations",
        description: "Sub chain for audit logs and business transactions in healthcare data exchange",
      },
    ],
    blockchainTransactions: [
      {
        id: "htx1",
        hash: "0xa1b2c3d4e5f6789012345678901234567890abcdef1234567890abcdef123456",
        type: "did_registration",
        from: "did:healthcare:hospital1",
        to: "IdentityRegistry",
        status: "confirmed",
        timestamp: "2024-01-20T10:30:00Z",
        blockNumber: 2456789,
        chainType: "main",
      },
      {
        id: "htx2",
        hash: "0xb2c3d4e5f6789012345678901234567890abcdef1234567890abcdef1234567",
        type: "audit_log",
        from: "did:healthcare:researcher1",
        to: "AuditContract",
        status: "confirmed",
        timestamp: "2024-01-20T09:15:00Z",
        blockNumber: 1234566,
        chainType: "sub",
      },
      {
        id: "htx3",
        hash: "0xc3d4e5f6789012345678901234567890abcdef1234567890abcdef12345678",
        type: "data_access",
        from: "did:healthcare:analyzer1",
        to: "DataContract",
        status: "pending",
        timestamp: "2024-01-20T11:45:00Z",
        blockNumber: 1234567,
        chainType: "sub",
      },
    ],
    auditLogs: [
      {
        id: "hal1",
        timestamp: "2024-01-20T10:30:00Z",
        action: "did_registration",
        actor: "did:healthcare:hospital1",
        target: "IdentityRegistry",
        details: "Registered new healthcare provider identity",
        blockchainTxId: "htx1",
        status: "success",
      },
      {
        id: "hal2", 
        timestamp: "2024-01-20T09:15:00Z",
        action: "data_transfer",
        actor: "did:healthcare:researcher1",
        target: "PatientDataset:123",
        details: "Transferred patient data for research analysis",
        blockchainTxId: "htx2",
        status: "success",
      },
    ],
  },
  
  finance: {
    dataOfferings: [
      {
        id: "f1",
        title: "Market Analytics Dataset",
        description: "Real-time financial market data and analytics",
        dataType: "restful",
        accessPolicy: "Commercial License",
        status: "active",
        registrationStatus: "registered",
        createdAt: "2024-01-10T10:00:00Z",
        sourceConfig: {
          apiEndpoint: "https://api.market-data.com/v1/analytics",
          method: "GET",
          headers: { "Content-Type": "application/json" },
        },
      },
      {
        id: "f2",
        title: "Credit Risk Models",
        description: "Machine learning models for credit risk assessment",
        dataType: "nas",
        accessPolicy: "Partner Only",
        status: "active",
        registrationStatus: "unregistered",
        createdAt: "2024-01-12T14:30:00Z",
        sourceConfig: {
          serverAddress: "192.168.100.50",
          sharePath: "/models/credit-risk",
          protocol: "smb",
        },
      },
    ],
    dataContracts: [
      {
        id: "fc1",
        name: "Financial Market Data Contract",
        contractAddress: "0xfinance123456789abcdef123456789abcdef123456",
        providerDID: "did:finance:bank123",
        consumerDID: "did:finance:fintech456",
        policy: "Commercial License",
        status: "active",
        createdAt: "2024-01-10T10:00:00Z",
        expiresAt: "2024-12-31T23:59:59Z",
        accessCount: 8750,
        dataVolume: "125.8 GB",
        maxAccessCount: 10000,
        violationCount: 0,
        isViolated: false,
        isExpired: false,
      },
    ],
    connectedConnectors: [
      {
        id: "fconn1",
        name: "Central Bank",
        did: "did:finance:central-bank-eu-123",
        status: "connected",
        lastSeen: "2024-01-15T09:00:00Z",
        offeringsCount: 25,
      },
      {
        id: "fconn2",
        name: "FinTech Alliance",
        did: "did:finance:fintech-alliance-456",
        status: "connected", 
        lastSeen: "2024-01-14T18:30:00Z",
        offeringsCount: 12,
      },
    ],
    digitalContracts: [],
    policyTemplates: [
      {
        id: "fp1",
        name: "Access Period Limitation",
        description: "Maximum session duration for financial data access - 4 hours",
        rules: [
          {
            id: "fr1",
            type: "access_period",
            name: "Session Timeout",
            description: "Maximum session duration for financial data access",
            value: 4,
            unit: "hours",
            isActive: true,
          },
        ],
        category: "access",
        severity: "high",
        enforcementType: "automatic",
        createdAt: "2024-01-08T10:00:00Z",
      },
      {
        id: "fp2",
        name: "Access Count Limitation",
        description: "Maximum data access requests per day - 1000 requests",
        rules: [
          {
            id: "fr2",
            type: "access_count",
            name: "Daily Access Limit",
            description: "Maximum data access requests per day",
            value: 1000,
            unit: "requests/day",
            isActive: true,
          },
        ],
        category: "usage",
        severity: "high",
        enforcementType: "automatic",
        createdAt: "2024-01-08T11:00:00Z",
      },
      {
        id: "fp3",
        name: "Identity Restriction",
        description: "Only authorized financial institutions can access",
        rules: [
          {
            id: "fr3",
            type: "identity_restriction",
            name: "Financial Institution Only",
            description: "Only authorized financial institutions can access",
            value: "financial_institution",
            isActive: true,
          },
        ],
        category: "compliance",
        severity: "high",
        enforcementType: "manual",
        createdAt: "2024-01-08T12:00:00Z",
      },
      {
        id: "fp4",
        name: "Encryption & Transmission Protection",
        description: "All financial data must use TLS 1.3 encryption",
        rules: [
          {
            id: "fr4",
            type: "encryption",
            name: "TLS 1.3 Encryption",
            description: "All financial data must use TLS 1.3 encryption",
            value: "TLS-1.3",
            isActive: true,
          },
        ],
        category: "compliance",
        severity: "high",
        enforcementType: "automatic",
        createdAt: "2024-01-08T13:00:00Z",
      },
      {
        id: "fp5",
        name: "Access IP Restriction",
        description: "Only specified IP addresses can access financial data",
        rules: [
          {
            id: "fr5",
            type: "ip_restriction",
            name: "IP Whitelist",
            description: "Only specified IP addresses can access financial data",
            value: "192.168.1.0/24,10.0.0.0/8",
            isActive: true,
          },
        ],
        category: "access",
        severity: "medium",
        enforcementType: "automatic",
        createdAt: "2024-01-08T14:00:00Z",
      },
      {
        id: "fp6",
        name: "Single Transfer Limit",
        description: "Maximum records per bulk transfer - 50000 records",
        rules: [
          {
            id: "fr6",
            type: "transfer_limit",
            name: "Bulk Transfer Limit",
            description: "Maximum records per bulk transfer",
            value: 50000,
            unit: "records",
            isActive: true,
          },
        ],
        category: "usage",
        severity: "medium",
        enforcementType: "automatic",
        createdAt: "2024-01-08T15:00:00Z",
      },
      {
        id: "fp7",
        name: "Data Transmission QPS Limit",
        description: "Maximum queries per second for financial APIs - 10 QPS",
        rules: [
          {
            id: "fr7",
            type: "qps_limit",
            name: "Query Rate Limit",
            description: "Maximum queries per second for financial APIs",
            value: 10,
            unit: "queries/second",
            isActive: true,
          },
        ],
        category: "usage",
        severity: "high",
        enforcementType: "automatic",
        createdAt: "2024-01-08T16:00:00Z",
      },
    ],
    contractTemplates: [
      {
        id: "fc1",
        name: "Basic Financial Access Contract",
        description: "Basic contract with session timeout and encryption",
        policyIds: ["fp1", "fp4"],
        policies: [],
        contractType: "multi_policy",
        status: "active",
        createdAt: "2024-01-08T10:00:00Z",
        usageCount: 25,
      },
      {
        id: "fc2",
        name: "High-Frequency Trading Contract",
        description: "Enhanced contract for trading data with all restrictions",
        policyIds: ["fp1", "fp2", "fp3", "fp4", "fp7"],
        policies: [],
        contractType: "multi_policy",
        status: "active",
        createdAt: "2024-01-10T11:00:00Z",
        usageCount: 12,
      },
      {
        id: "fc3",
        name: "Secure Financial Data Contract",
        description: "Maximum security contract with all access controls",
        policyIds: ["fp1", "fp3", "fp4", "fp5", "fp6", "fp7"],
        policies: [],
        contractType: "multi_policy",
        status: "active",
        createdAt: "2024-01-12T15:00:00Z",
        usageCount: 8,
      },
    ],
    externalOfferings: [
      {
        id: "fe1",
        title: "ESG Ratings Database",
        description: "Environmental, Social, and Governance ratings for listed companies",
        dataType: "JSON/XML",
        provider: "ESG Analytics Inc",
        providerDID: "did:finance:esg123",
        accessPolicy: "Subscription",
        category: "analytics",
        lastUpdated: "2024-01-15T10:00:00Z",
        size: "1.8 GB",
        price: "$5000/month",
      },
    ],
    dataRequests: [
      {
        id: "fdr1",
        offeringId: "fe1",
        offeringTitle: "ESG Ratings Database",
        provider: "ESG Analytics Inc",
        requestedAt: "2024-01-19T10:00:00Z",
        status: "approved",
        accessMode: "api",
        purpose: "ESG investment analysis and portfolio optimization",
      },
      {
        id: "fdr2",
        offeringId: "fe2",
        offeringTitle: "Financial Market Data",
        provider: "Market Data Corp",
        requestedAt: "2024-01-20T08:30:00Z",
        status: "pending",
        accessMode: "download",
        purpose: "Risk assessment and algorithmic trading",
      },
    ],
    blockchainNetworks: [
      {
        id: "finance-main",
        name: "Financial Identity Chain",
        type: "ZLTC",
        chainType: "main",
        chainId: 2001,
        status: "connected",
        curveAlgorithm: "Secp256k1",
        witnessNodes: 9,
        consensusNodes: 5,
        blockHeight: 3567890,
        purpose: "Identity Management",
        description: "Main chain for financial institution identity verification and KYC processes",
      },
      {
        id: "finance-sub",
        name: "Financial Business Chain",
        type: "ZLTC",
        chainType: "sub",
        chainId: 2002,
        status: "connected",
        curveAlgorithm: "Sm2p256v1",
        witnessNodes: 7,
        consensusNodes: 4,
        blockHeight: 2345678,
        purpose: "Business Operations",
        description: "Sub chain for transaction audit logs and compliance monitoring",
      },
    ],
    blockchainTransactions: [
      {
        id: "ftx1",
        hash: "0xf1a2b3c4d5e6789012345678901234567890abcdef1234567890abcdef123456",
        type: "did_registration",
        from: "did:finance:bank1",
        to: "FinancialRegistry",
        status: "confirmed",
        timestamp: "2024-01-20T14:20:00Z",
        blockNumber: 3567890,
        chainType: "main",
      },
      {
        id: "ftx2",
        hash: "0xf2b3c4d5e6789012345678901234567890abcdef1234567890abcdef1234567",
        type: "audit_log",
        from: "did:finance:trader1",
        to: "ComplianceContract",
        status: "confirmed",
        timestamp: "2024-01-20T13:45:00Z",
        blockNumber: 2345677,
        chainType: "sub",
      },
    ],
    auditLogs: [
      {
        id: "fal1",
        timestamp: "2024-01-20T14:20:00Z",
        action: "did_registration",
        actor: "did:finance:bank1",
        target: "FinancialRegistry",
        details: "Registered new financial institution identity",
        blockchainTxId: "ftx1",
        status: "success",
      },
      {
        id: "fal2",
        timestamp: "2024-01-20T13:45:00Z",
        action: "data_transfer",
        actor: "did:finance:trader1",
        target: "TradingData:456",
        details: "High-frequency trading data transfer",
        blockchainTxId: "ftx2",
        status: "success",
      },
    ],
  },

  mobility: {
    dataOfferings: [
      {
        id: "m1",
        title: "Traffic Flow Data",
        description: "Real-time traffic flow and congestion data",
        dataType: "restful",
        accessPolicy: "Open Data",
        status: "active",
        registrationStatus: "registered",
        createdAt: "2024-01-10T10:00:00Z",
        sourceConfig: {
          apiEndpoint: "https://api.city-traffic.gov/v1/flow",
          method: "GET",
        },
      },
      {
        id: "m2",
        title: "Public Transport Schedule",
        description: "Dynamic public transportation schedules and delays",
        dataType: "local_file",
        accessPolicy: "Municipal License",
        status: "active",
        registrationStatus: "registering",
        createdAt: "2024-01-12T14:30:00Z",
        sourceConfig: {
          filePath: "/data/transport/gtfs-realtime.json",
          format: "JSON",
          fileSize: "850 MB",
        },
      },
    ],
    dataContracts: [
      {
        id: "mc1",
        name: "City Traffic Data Contract",
        contractAddress: "0xmobility123456789abcdef123456789abcdef12345",
        providerDID: "did:mobility:city123",
        consumerDID: "did:mobility:transport456",
        policy: "Open Access",
        status: "transferring",
        createdAt: "2024-01-10T10:00:00Z",
        accessCount: 567,
        dataVolume: "23.4 GB",
        maxAccessCount: 1000,
        violationCount: 0,
        isViolated: false,
        isExpired: false,
      },
    ],
    connectedConnectors: [
      {
        id: "mconn1",
        name: "Smart City Platform",
        did: "did:mobility:smart-city-123",
        status: "connected",
        lastSeen: "2024-01-15T07:45:00Z",
        offeringsCount: 20,
      },
    ],
    digitalContracts: [],
    policyTemplates: [
      {
        id: "mp1",
        name: "Access Period Limitation",
        description: "Maximum time window for real-time mobility data - 24 hours",
        rules: [
          {
            id: "mr1",
            type: "access_period",
            name: "Real-time Access Window",
            description: "Maximum time window for real-time mobility data",
            value: 24,
            unit: "hours",
            isActive: true,
          },
        ],
        category: "access",
        severity: "medium",
        enforcementType: "automatic",
        createdAt: "2024-01-09T08:00:00Z",
      },
      {
        id: "mp2",
        name: "Access Count Limitation",
        description: "Maximum API calls per day for mobility data - 5000 requests",
        rules: [
          {
            id: "mr2",
            type: "access_count",
            name: "Daily API Limit",
            description: "Maximum API calls per day for mobility data",
            value: 5000,
            unit: "requests/day",
            isActive: true,
          },
        ],
        category: "usage",
        severity: "medium",
        enforcementType: "automatic",
        createdAt: "2024-01-09T09:00:00Z",
      },
      {
        id: "mp3",
        name: "Identity Restriction",
        description: "Only registered mobility service providers can access",
        rules: [
          {
            id: "mr3",
            type: "identity_restriction",
            name: "Mobility Service Provider",
            description: "Only registered mobility service providers can access",
            value: "mobility_provider",
            isActive: true,
          },
        ],
        category: "compliance",
        severity: "medium",
        enforcementType: "manual",
        createdAt: "2024-01-09T10:00:00Z",
      },
      {
        id: "mp4",
        name: "Data Transmission QPS Limit",
        description: "Maximum API calls per second for mobility services - 50 QPS",
        rules: [
          {
            id: "mr4",
            type: "qps_limit",
            name: "API Rate Limit",
            description: "Maximum API calls per second for mobility services",
            value: 50,
            unit: "calls/second",
            isActive: true,
          },
        ],
        category: "usage",
        severity: "medium",
        enforcementType: "automatic",
        createdAt: "2024-01-09T11:00:00Z",
      },
    ],
    contractTemplates: [
      {
        id: "mc1",
        name: "Basic Mobility Data Contract",
        description: "Basic contract for mobility data access with time limits",
        policyIds: ["mp1", "mp2"],
        policies: [],
        contractType: "multi_policy",
        status: "active",
        createdAt: "2024-01-09T08:00:00Z",
        usageCount: 18,
      },
      {
        id: "mc2",
        name: "Professional Mobility Service Contract",
        description: "Comprehensive contract for registered mobility service providers",
        policyIds: ["mp1", "mp2", "mp3", "mp4"],
        policies: [],
        contractType: "multi_policy",
        status: "active",
        createdAt: "2024-01-12T10:00:00Z",
        usageCount: 7,
      },
    ],
    externalOfferings: [
      {
        id: "me1",
        title: "Weather Impact on Transport",
        description: "Weather data correlated with transportation disruptions",
        dataType: "JSON",
        provider: "Weather & Transport Analytics",
        providerDID: "did:mobility:weather123",
        accessPolicy: "Open Access",
        category: "analytics",
        lastUpdated: "2024-01-15T06:00:00Z",
        size: "3.1 GB",
      },
    ],
    dataRequests: [
      {
        id: "mdr1",
        offeringId: "me1",
        offeringTitle: "Weather Impact on Transport",
        provider: "Weather & Transport Analytics",
        requestedAt: "2024-01-20T12:00:00Z",
        status: "approved",
        accessMode: "api",
        purpose: "Smart city traffic optimization and route planning",
      },
      {
        id: "mdr2",
        offeringId: "me2",
        offeringTitle: "Public Transport Data",
        provider: "City Transport Authority",
        requestedAt: "2024-01-18T16:45:00Z",
        status: "completed",
        accessMode: "download",
        purpose: "Urban mobility analysis and service improvement",
      },
    ],
    blockchainNetworks: [
      {
        id: "mobility-main",
        name: "Mobility Identity Chain",
        type: "ZLTC",
        chainType: "main",
        chainId: 3001,
        status: "connected",
        curveAlgorithm: "Secp256k1",
        witnessNodes: 5,
        consensusNodes: 3,
        blockHeight: 1789012,
        purpose: "Identity Management",
        description: "Main chain for mobility service provider identity verification",
      },
      {
        id: "mobility-sub",
        name: "Mobility Business Chain",
        type: "ZLTC",
        chainType: "sub",
        chainId: 3002,
        status: "connected",
        curveAlgorithm: "Sm2p256v1",
        witnessNodes: 3,
        consensusNodes: 2,
        blockHeight: 987654,
        purpose: "Business Operations",
        description: "Sub chain for transportation data audit and smart city operations",
      },
    ],
    blockchainTransactions: [
      {
        id: "mtx1",
        hash: "0xm1a2b3c4d5e6789012345678901234567890abcdef1234567890abcdef123456",
        type: "did_registration",
        from: "did:mobility:transport1",
        to: "MobilityRegistry",
        status: "confirmed",
        timestamp: "2024-01-20T16:10:00Z",
        blockNumber: 1789012,
        chainType: "main",
      },
      {
        id: "mtx2",
        hash: "0xm2b3c4d5e6789012345678901234567890abcdef1234567890abcdef1234567",
        type: "audit_log",
        from: "did:mobility:city1",
        to: "TrafficContract",
        status: "confirmed",
        timestamp: "2024-01-20T15:30:00Z",
        blockNumber: 987653,
        chainType: "sub",
      },
    ],
    auditLogs: [
      {
        id: "mal1",
        timestamp: "2024-01-20T16:10:00Z",
        action: "did_registration",
        actor: "did:mobility:transport1",
        target: "MobilityRegistry",
        details: "Registered new transport service provider",
        blockchainTxId: "mtx1",
        status: "success",
      },
      {
        id: "mal2",
        timestamp: "2024-01-20T15:30:00Z",
        action: "data_transfer",
        actor: "did:mobility:city1",
        target: "TrafficData:789",
        details: "Real-time traffic data update",
        blockchainTxId: "mtx2",
        status: "success",
      },
    ],
  },

  energy: {
    dataOfferings: [
      {
        id: "e1",
        title: "Grid Load Forecasting",
        description: "Electrical grid load prediction models and historical data",
        dataType: "s3",
        accessPolicy: "Utility Partners",
        status: "inactive",
        registrationStatus: "failed",
        createdAt: "2024-01-10T10:00:00Z",
        sourceConfig: {
          bucketName: "energy-grid-data",
          objectKey: "forecasting/load-models",
          region: "eu-central-1",
        },
      },
    ],
    dataContracts: [
      {
        id: "ec1",
        name: "Critical Infrastructure Data Contract",
        contractAddress: "0xenergy000111222333444555666777888999aaabbb",
        providerDID: "did:energy:grid123",
        consumerDID: "did:energy:operator456",
        policy: "Critical Infrastructure",
        status: "data_unavailable",
        createdAt: "2024-01-05T10:00:00Z",
        expiresAt: "2024-07-05T23:59:59Z",
        accessCount: 0,
        dataVolume: "0 GB",
        maxAccessCount: 50,
        violationCount: 0,
        isViolated: false,
        isExpired: false,
      },
    ],
    connectedConnectors: [
      {
        id: "econn1",
        name: "Energy Grid Operator",
        did: "did:energy:grid-op-123",
        status: "pending",
        lastSeen: "2024-01-10T12:00:00Z",
        offeringsCount: 5,
      },
    ],
    digitalContracts: [],
    policyTemplates: [
      {
        id: "ep1",
        name: "Access Period Limitation",
        description: "Critical infrastructure access window - 2 hours",
        rules: [
          {
            id: "er1",
            type: "access_period",
            name: "Critical Access Window",
            description: "Maximum access period for critical infrastructure data",
            value: 2,
            unit: "hours",
            isActive: true,
          },
        ],
        category: "access",
        severity: "high",
        enforcementType: "automatic",
        createdAt: "2024-01-05T10:00:00Z",
      },
      {
        id: "ep2",
        name: "Access Count Limitation",
        description: "Very limited access requests per month - 10 requests",
        rules: [
          {
            id: "er2",
            type: "access_count",
            name: "Strict Access Limit",
            description: "Very limited access requests per month",
            value: 10,
            unit: "requests/month",
            isActive: true,
          },
        ],
        category: "compliance",
        severity: "high",
        enforcementType: "manual",
        createdAt: "2024-01-05T11:00:00Z",
      },
      {
        id: "ep3",
        name: "Identity Restriction",
        description: "Requires government security clearance",
        rules: [
          {
            id: "er3",
            type: "identity_restriction",
            name: "Government Authorization",
            description: "Requires government security clearance",
            value: "security_clearance_required",
            isActive: true,
          },
        ],
        category: "compliance",
        severity: "high",
        enforcementType: "manual",
        createdAt: "2024-01-05T12:00:00Z",
      },
      {
        id: "ep4",
        name: "Encryption & Transmission Protection",
        description: "All data must use military-grade encryption",
        rules: [
          {
            id: "er4",
            type: "encryption",
            name: "Military-Grade Encryption",
            description: "All data must use military-grade encryption",
            value: "AES-256-GCM",
            isActive: true,
          },
        ],
        category: "compliance",
        severity: "high",
        enforcementType: "automatic",
        createdAt: "2024-01-05T13:00:00Z",
      },
    ],
    contractTemplates: [
      {
        id: "ec1",
        name: "Critical Infrastructure Contract",
        description: "Maximum security contract for critical energy infrastructure data",
        policyIds: ["ep1", "ep2", "ep3", "ep4"],
        policies: [],
        contractType: "multi_policy",
        status: "draft",
        createdAt: "2024-01-05T10:00:00Z",
        usageCount: 2,
      },
    ],
    externalOfferings: [],
    dataRequests: [
      {
        id: "edr1",
        offeringId: "ee1",
        offeringTitle: "Grid Load Forecasting",
        provider: "Energy Analytics Corp",
        requestedAt: "2024-01-19T15:00:00Z",
        status: "pending",
        accessMode: "api",
        purpose: "Critical infrastructure monitoring and load balancing",
      },
    ],
    blockchainNetworks: [
      {
        id: "energy-main",
        name: "Energy Identity Chain",
        type: "ZLTC",
        chainType: "main",
        chainId: 4001,
        status: "connected",
        curveAlgorithm: "Sm2p256v1",
        witnessNodes: 11,
        consensusNodes: 7,
        blockHeight: 4567890,
        purpose: "Identity Management",
        description: "Main chain for critical energy infrastructure identity verification",
      },
      {
        id: "energy-sub",
        name: "Energy Business Chain",
        type: "ZLTC",
        chainType: "sub",
        chainId: 4002,
        status: "connected",
        curveAlgorithm: "Sm2p256v1",
        witnessNodes: 9,
        consensusNodes: 5,
        blockHeight: 3456789,
        purpose: "Business Operations",
        description: "Sub chain for energy grid operations and critical infrastructure audit logs",
      },
    ],
    blockchainTransactions: [
      {
        id: "etx1",
        hash: "0xe1a2b3c4d5e6789012345678901234567890abcdef1234567890abcdef123456",
        type: "did_registration",
        from: "did:energy:grid1",
        to: "EnergyRegistry",
        status: "confirmed",
        timestamp: "2024-01-20T18:00:00Z",
        blockNumber: 4567890,
        chainType: "main",
      },
      {
        id: "etx2",
        hash: "0xe2b3c4d5e6789012345678901234567890abcdef1234567890abcdef1234567",
        type: "audit_log",
        from: "did:energy:operator1",
        to: "GridContract",
        status: "confirmed",
        timestamp: "2024-01-20T17:30:00Z",
        blockNumber: 3456788,
        chainType: "sub",
      },
    ],
    auditLogs: [
      {
        id: "eal1",
        timestamp: "2024-01-20T18:00:00Z",
        action: "did_registration",
        actor: "did:energy:grid1",
        target: "EnergyRegistry",
        details: "Registered new energy grid operator",
        blockchainTxId: "etx1",
        status: "success",
      },
      {
        id: "eal2",
        timestamp: "2024-01-20T17:30:00Z",
        action: "data_transfer",
        actor: "did:energy:operator1",
        target: "GridData:101",
        details: "Critical grid load data transfer",
        blockchainTxId: "etx2",
        status: "success",
      },
    ],
  },
};

export function getDataForSpace(dataSpaceId: string) {
  return dataSpaceConfigs[dataSpaceId] || dataSpaceConfigs.healthcare;
}
