// 基于数据空间的数据服务
export interface DataSpaceDataConfig {
  [key: string]: {
    dataOfferings: any[];
    dataContracts: any[];
    connectedConnectors: any[];
    digitalContracts: any[];
    policyTemplates: any[];
    contractTemplates: any[];
    externalOfferings: any[];
    dataRequests: any[];
  };
}

export const dataSpaceConfigs: DataSpaceDataConfig = {
  healthcare: {
    dataOfferings: [
      {
        id: "h1",
        title: "Patient Demographics Dataset",
        description: "Anonymized patient demographic data for healthcare analytics",
        dataType: "CSV",
        accessPolicy: "GDPR Compliant",
        status: "active",
        createdAt: "2024-01-10T10:00:00Z",
      },
      {
        id: "h2", 
        title: "Medical Imaging Archive",
        description: "De-identified medical imaging data for research",
        dataType: "DICOM",
        accessPolicy: "Research Only",
        status: "active",
        createdAt: "2024-01-12T14:30:00Z",
      },
    ],
    dataContracts: [
      {
        id: "hc1",
        contractAddress: "0xhealth123456789abcdef123456789abcdef123456",
        providerDID: "did:health:provider123",
        consumerDID: "did:health:consumer456",
        policy: "GDPR Compliance",
        status: "active",
        createdAt: "2024-01-10T10:00:00Z",
        expiresAt: "2024-12-31T23:59:59Z",
      },
      {
        id: "hc2",
        contractAddress: "0xhealth987654321fedcba987654321fedcba987654",
        providerDID: "did:health:provider789",
        consumerDID: "did:health:consumer123",
        policy: "Medical Research",
        status: "active",
        createdAt: "2024-01-12T14:30:00Z",
      },
    ],
    connectedConnectors: [
      {
        id: "hconn1",
        name: "Hospital Network EU",
        did: "did:health:hospital-eu-123",
        status: "connected",
        lastSeen: "2024-01-15T08:30:00Z",
        offeringsCount: 15,
      },
      {
        id: "hconn2", 
        name: "Research Institute",
        did: "did:health:research-inst-456",
        status: "connected",
        lastSeen: "2024-01-14T16:45:00Z",
        offeringsCount: 8,
      },
    ],
    digitalContracts: [],
    policyTemplates: [
      {
        id: "hp1",
        name: "Access Period Limitation",
        description: "Maximum access period for patient data - 30 days",
        rules: [
          {
            id: "hr1",
            type: "access_period",
            name: "Access Period Limitation",
            description: "Maximum access period for patient data",
            value: 30,
            unit: "days",
            isActive: true,
          },
        ],
        category: "access",
        severity: "high",
        enforcementType: "automatic",
        createdAt: "2024-01-10T10:00:00Z",
      },
      {
        id: "hp2",
        name: "Access Count Limitation",
        description: "Maximum number of data access requests per month - 100 requests",
        rules: [
          {
            id: "hr2",
            type: "access_count",
            name: "Access Count Limit",
            description: "Maximum number of data access requests per month",
            value: 100,
            unit: "requests/month",
            isActive: true,
          },
        ],
        category: "usage",
        severity: "medium",
        enforcementType: "automatic",
        createdAt: "2024-01-10T11:00:00Z",
      },
      {
        id: "hp3",
        name: "Identity Restriction",
        description: "Only verified medical professionals can access",
        rules: [
          {
            id: "hr3",
            type: "identity_restriction",
            name: "Medical Professional Only",
            description: "Only verified medical professionals can access",
            value: "medical_professional",
            isActive: true,
          },
        ],
        category: "compliance",
        severity: "high",
        enforcementType: "manual",
        createdAt: "2024-01-10T12:00:00Z",
      },
      {
        id: "hp4",
        name: "Encryption & Transmission Protection",
        description: "All data must be encrypted with AES-256",
        rules: [
          {
            id: "hr4",
            type: "encryption",
            name: "End-to-End Encryption",
            description: "All data must be encrypted with AES-256",
            value: "AES-256",
            isActive: true,
          },
        ],
        category: "compliance",
        severity: "high",
        enforcementType: "automatic",
        createdAt: "2024-01-10T13:00:00Z",
      },
      {
        id: "hp5",
        name: "Access IP Restriction",
        description: "Only specified IP addresses can access healthcare data",
        rules: [
          {
            id: "hr5",
            type: "ip_restriction",
            name: "IP Whitelist",
            description: "Only specified IP addresses can access healthcare data",
            value: "192.168.100.0/24,10.20.0.0/16",
            isActive: true,
          },
        ],
        category: "access",
        severity: "medium",
        enforcementType: "automatic",
        createdAt: "2024-01-10T14:00:00Z",
      },
      {
        id: "hp6",
        name: "Single Transfer Limit",
        description: "Maximum data transfer per session - 1000 records",
        rules: [
          {
            id: "hr6",
            type: "transfer_limit",
            name: "Transfer Volume Limit",
            description: "Maximum data transfer per session",
            value: 1000,
            unit: "records",
            isActive: true,
          },
        ],
        category: "usage",
        severity: "medium",
        enforcementType: "automatic",
        createdAt: "2024-01-10T15:00:00Z",
      },
      {
        id: "hp7",
        name: "Data Transmission QPS Limit",
        description: "Maximum queries per second for healthcare APIs - 5 QPS",
        rules: [
          {
            id: "hr7",
            type: "qps_limit",
            name: "Query Rate Limit",
            description: "Maximum queries per second for healthcare APIs",
            value: 5,
            unit: "queries/second",
            isActive: true,
          },
        ],
        category: "usage",
        severity: "medium",
        enforcementType: "automatic",
        createdAt: "2024-01-10T16:00:00Z",
      },
    ],
    contractTemplates: [
      {
        id: "hc1",
        name: "Basic Healthcare Access Contract",
        description: "Basic contract with access period and encryption requirements",
        policyIds: ["hp1", "hp4"],
        policies: [],
        contractType: "multi_policy",
        status: "active",
        createdAt: "2024-01-10T10:00:00Z",
        usageCount: 15,
      },
      {
        id: "hc2",
        name: "Medical Research Contract", 
        description: "Comprehensive contract for medical research with full restrictions",
        policyIds: ["hp1", "hp2", "hp3", "hp4", "hp6"],
        policies: [],
        contractType: "multi_policy",
        status: "active",
        createdAt: "2024-01-15T09:00:00Z",
        usageCount: 8,
      },
      {
        id: "hc3",
        name: "Secure Access Contract",
        description: "High-security contract with all access controls",
        policyIds: ["hp1", "hp3", "hp4", "hp5", "hp7"],
        policies: [],
        contractType: "multi_policy",
        status: "active",
        createdAt: "2024-01-18T14:00:00Z",
        usageCount: 12,
      },
    ],
    externalOfferings: [
      {
        id: "he1",
        title: "Clinical Trial Data",
        description: "Phase III clinical trial datasets",
        dataType: "JSON/CSV",
        provider: "Pharma Research Corp",
        providerDID: "did:health:pharma123",
        accessPolicy: "Research License",
        category: "research",
        lastUpdated: "2024-01-15T08:00:00Z",
        size: "5.2 GB",
        price: "$2000/month",
      },
    ],
    dataRequests: [],
  },
  
  finance: {
    dataOfferings: [
      {
        id: "f1",
        title: "Market Analytics Dataset",
        description: "Real-time financial market data and analytics",
        dataType: "JSON",
        accessPolicy: "Commercial License",
        status: "active",
        createdAt: "2024-01-10T10:00:00Z",
      },
      {
        id: "f2",
        title: "Credit Risk Models",
        description: "Machine learning models for credit risk assessment",
        dataType: "Model",
        accessPolicy: "Partner Only",
        status: "active", 
        createdAt: "2024-01-12T14:30:00Z",
      },
    ],
    dataContracts: [
      {
        id: "fc1",
        contractAddress: "0xfinance123456789abcdef123456789abcdef123456",
        providerDID: "did:finance:bank123",
        consumerDID: "did:finance:fintech456",
        policy: "Commercial License",
        status: "active",
        createdAt: "2024-01-10T10:00:00Z",
        expiresAt: "2024-12-31T23:59:59Z",
      },
    ],
    connectedConnectors: [
      {
        id: "fconn1",
        name: "Central Bank",
        did: "did:finance:central-bank-eu-123",
        status: "connected",
        lastSeen: "2024-01-15T09:00:00Z",
        offeringsCount: 25,
      },
      {
        id: "fconn2",
        name: "FinTech Alliance",
        did: "did:finance:fintech-alliance-456",
        status: "connected", 
        lastSeen: "2024-01-14T18:30:00Z",
        offeringsCount: 12,
      },
    ],
    digitalContracts: [],
    policyTemplates: [
      {
        id: "fp1",
        name: "Access Period Limitation",
        description: "Maximum session duration for financial data access - 4 hours",
        rules: [
          {
            id: "fr1",
            type: "access_period",
            name: "Session Timeout",
            description: "Maximum session duration for financial data access",
            value: 4,
            unit: "hours",
            isActive: true,
          },
        ],
        category: "access",
        severity: "high",
        enforcementType: "automatic",
        createdAt: "2024-01-08T10:00:00Z",
      },
      {
        id: "fp2",
        name: "Access Count Limitation",
        description: "Maximum data access requests per day - 1000 requests",
        rules: [
          {
            id: "fr2",
            type: "access_count",
            name: "Daily Access Limit",
            description: "Maximum data access requests per day",
            value: 1000,
            unit: "requests/day",
            isActive: true,
          },
        ],
        category: "usage",
        severity: "high",
        enforcementType: "automatic",
        createdAt: "2024-01-08T11:00:00Z",
      },
      {
        id: "fp3",
        name: "Identity Restriction",
        description: "Only authorized financial institutions can access",
        rules: [
          {
            id: "fr3",
            type: "identity_restriction",
            name: "Financial Institution Only",
            description: "Only authorized financial institutions can access",
            value: "financial_institution",
            isActive: true,
          },
        ],
        category: "compliance",
        severity: "high",
        enforcementType: "manual",
        createdAt: "2024-01-08T12:00:00Z",
      },
      {
        id: "fp4",
        name: "Encryption & Transmission Protection",
        description: "All financial data must use TLS 1.3 encryption",
        rules: [
          {
            id: "fr4",
            type: "encryption",
            name: "TLS 1.3 Encryption",
            description: "All financial data must use TLS 1.3 encryption",
            value: "TLS-1.3",
            isActive: true,
          },
        ],
        category: "compliance",
        severity: "high",
        enforcementType: "automatic",
        createdAt: "2024-01-08T13:00:00Z",
      },
      {
        id: "fp5",
        name: "Access IP Restriction",
        description: "Only specified IP addresses can access financial data",
        rules: [
          {
            id: "fr5",
            type: "ip_restriction",
            name: "IP Whitelist",
            description: "Only specified IP addresses can access financial data",
            value: "192.168.1.0/24,10.0.0.0/8",
            isActive: true,
          },
        ],
        category: "access",
        severity: "medium",
        enforcementType: "automatic",
        createdAt: "2024-01-08T14:00:00Z",
      },
      {
        id: "fp6",
        name: "Single Transfer Limit",
        description: "Maximum records per bulk transfer - 50000 records",
        rules: [
          {
            id: "fr6",
            type: "transfer_limit",
            name: "Bulk Transfer Limit",
            description: "Maximum records per bulk transfer",
            value: 50000,
            unit: "records",
            isActive: true,
          },
        ],
        category: "usage",
        severity: "medium",
        enforcementType: "automatic",
        createdAt: "2024-01-08T15:00:00Z",
      },
      {
        id: "fp7",
        name: "Data Transmission QPS Limit",
        description: "Maximum queries per second for financial APIs - 10 QPS",
        rules: [
          {
            id: "fr7",
            type: "qps_limit",
            name: "Query Rate Limit",
            description: "Maximum queries per second for financial APIs",
            value: 10,
            unit: "queries/second",
            isActive: true,
          },
        ],
        category: "usage",
        severity: "high",
        enforcementType: "automatic",
        createdAt: "2024-01-08T16:00:00Z",
      },
    ],
    contractTemplates: [
      {
        id: "fc1",
        name: "Basic Financial Access Contract",
        description: "Basic contract with session timeout and encryption",
        policyIds: ["fp1", "fp4"],
        policies: [],
        contractType: "multi_policy",
        status: "active",
        createdAt: "2024-01-08T10:00:00Z",
        usageCount: 25,
      },
      {
        id: "fc2",
        name: "High-Frequency Trading Contract",
        description: "Enhanced contract for trading data with all restrictions",
        policyIds: ["fp1", "fp2", "fp3", "fp4", "fp7"],
        policies: [],
        contractType: "multi_policy",
        status: "active",
        createdAt: "2024-01-10T11:00:00Z",
        usageCount: 12,
      },
      {
        id: "fc3",
        name: "Secure Financial Data Contract",
        description: "Maximum security contract with all access controls",
        policyIds: ["fp1", "fp3", "fp4", "fp5", "fp6", "fp7"],
        policies: [],
        contractType: "multi_policy",
        status: "active",
        createdAt: "2024-01-12T15:00:00Z",
        usageCount: 8,
      },
    ],
    externalOfferings: [
      {
        id: "fe1",
        title: "ESG Ratings Database",
        description: "Environmental, Social, and Governance ratings for listed companies",
        dataType: "JSON/XML",
        provider: "ESG Analytics Inc",
        providerDID: "did:finance:esg123",
        accessPolicy: "Subscription",
        category: "analytics",
        lastUpdated: "2024-01-15T10:00:00Z",
        size: "1.8 GB",
        price: "$5000/month",
      },
    ],
    dataRequests: [],
  },

  mobility: {
    dataOfferings: [
      {
        id: "m1",
        title: "Traffic Flow Data",
        description: "Real-time traffic flow and congestion data",
        dataType: "JSON",
        accessPolicy: "Open Data",
        status: "active",
        createdAt: "2024-01-10T10:00:00Z",
      },
      {
        id: "m2",
        title: "Public Transport Schedule",
        description: "Dynamic public transportation schedules and delays",
        dataType: "GTFS",
        accessPolicy: "Municipal License",
        status: "active",
        createdAt: "2024-01-12T14:30:00Z",
      },
    ],
    dataContracts: [
      {
        id: "mc1",
        contractAddress: "0xmobility123456789abcdef123456789abcdef12345",
        providerDID: "did:mobility:city123",
        consumerDID: "did:mobility:transport456",
        policy: "Open Access",
        status: "active",
        createdAt: "2024-01-10T10:00:00Z",
      },
    ],
    connectedConnectors: [
      {
        id: "mconn1",
        name: "Smart City Platform",
        did: "did:mobility:smart-city-123",
        status: "connected",
        lastSeen: "2024-01-15T07:45:00Z",
        offeringsCount: 20,
      },
    ],
    digitalContracts: [],
    policyTemplates: [
      {
        id: "mp1",
        name: "Access Period Limitation",
        description: "Maximum time window for real-time mobility data - 24 hours",
        rules: [
          {
            id: "mr1",
            type: "access_period",
            name: "Real-time Access Window",
            description: "Maximum time window for real-time mobility data",
            value: 24,
            unit: "hours",
            isActive: true,
          },
        ],
        category: "access",
        severity: "medium",
        enforcementType: "automatic",
        createdAt: "2024-01-09T08:00:00Z",
      },
      {
        id: "mp2",
        name: "Access Count Limitation",
        description: "Maximum API calls per day for mobility data - 5000 requests",
        rules: [
          {
            id: "mr2",
            type: "access_count",
            name: "Daily API Limit",
            description: "Maximum API calls per day for mobility data",
            value: 5000,
            unit: "requests/day",
            isActive: true,
          },
        ],
        category: "usage",
        severity: "medium",
        enforcementType: "automatic",
        createdAt: "2024-01-09T09:00:00Z",
      },
      {
        id: "mp3",
        name: "Identity Restriction",
        description: "Only registered mobility service providers can access",
        rules: [
          {
            id: "mr3",
            type: "identity_restriction",
            name: "Mobility Service Provider",
            description: "Only registered mobility service providers can access",
            value: "mobility_provider",
            isActive: true,
          },
        ],
        category: "compliance",
        severity: "medium",
        enforcementType: "manual",
        createdAt: "2024-01-09T10:00:00Z",
      },
      {
        id: "mp4",
        name: "Data Transmission QPS Limit",
        description: "Maximum API calls per second for mobility services - 50 QPS",
        rules: [
          {
            id: "mr4",
            type: "qps_limit",
            name: "API Rate Limit",
            description: "Maximum API calls per second for mobility services",
            value: 50,
            unit: "calls/second",
            isActive: true,
          },
        ],
        category: "usage",
        severity: "medium",
        enforcementType: "automatic",
        createdAt: "2024-01-09T11:00:00Z",
      },
    ],
    contractTemplates: [
      {
        id: "mc1",
        name: "Basic Mobility Data Contract",
        description: "Basic contract for mobility data access with time limits",
        policyIds: ["mp1", "mp2"],
        policies: [],
        contractType: "multi_policy",
        status: "active",
        createdAt: "2024-01-09T08:00:00Z",
        usageCount: 18,
      },
      {
        id: "mc2",
        name: "Professional Mobility Service Contract",
        description: "Comprehensive contract for registered mobility service providers",
        policyIds: ["mp1", "mp2", "mp3", "mp4"],
        policies: [],
        contractType: "multi_policy",
        status: "active",
        createdAt: "2024-01-12T10:00:00Z",
        usageCount: 7,
      },
    ],
    externalOfferings: [
      {
        id: "me1",
        title: "Weather Impact on Transport",
        description: "Weather data correlated with transportation disruptions",
        dataType: "JSON",
        provider: "Weather & Transport Analytics",
        providerDID: "did:mobility:weather123",
        accessPolicy: "Open Access",
        category: "analytics",
        lastUpdated: "2024-01-15T06:00:00Z",
        size: "3.1 GB",
      },
    ],
    dataRequests: [],
  },

  energy: {
    dataOfferings: [
      {
        id: "e1",
        title: "Grid Load Forecasting",
        description: "Electrical grid load prediction models and historical data",
        dataType: "Time Series",
        accessPolicy: "Utility Partners",
        status: "inactive",
        createdAt: "2024-01-10T10:00:00Z",
      },
    ],
    dataContracts: [],
    connectedConnectors: [
      {
        id: "econn1",
        name: "Energy Grid Operator",
        did: "did:energy:grid-op-123",
        status: "pending",
        lastSeen: "2024-01-10T12:00:00Z",
        offeringsCount: 5,
      },
    ],
    digitalContracts: [],
    policyTemplates: [
      {
        id: "ep1",
        name: "Access Period Limitation",
        description: "Critical infrastructure access window - 2 hours",
        rules: [
          {
            id: "er1",
            type: "access_period",
            name: "Critical Access Window",
            description: "Maximum access period for critical infrastructure data",
            value: 2,
            unit: "hours",
            isActive: true,
          },
        ],
        category: "access",
        severity: "high",
        enforcementType: "automatic",
        createdAt: "2024-01-05T10:00:00Z",
      },
      {
        id: "ep2",
        name: "Access Count Limitation",
        description: "Very limited access requests per month - 10 requests",
        rules: [
          {
            id: "er2",
            type: "access_count",
            name: "Strict Access Limit",
            description: "Very limited access requests per month",
            value: 10,
            unit: "requests/month",
            isActive: true,
          },
        ],
        category: "compliance",
        severity: "high",
        enforcementType: "manual",
        createdAt: "2024-01-05T11:00:00Z",
      },
      {
        id: "ep3",
        name: "Identity Restriction",
        description: "Requires government security clearance",
        rules: [
          {
            id: "er3",
            type: "identity_restriction",
            name: "Government Authorization",
            description: "Requires government security clearance",
            value: "security_clearance_required",
            isActive: true,
          },
        ],
        category: "compliance",
        severity: "high",
        enforcementType: "manual",
        createdAt: "2024-01-05T12:00:00Z",
      },
      {
        id: "ep4",
        name: "Encryption & Transmission Protection",
        description: "All data must use military-grade encryption",
        rules: [
          {
            id: "er4",
            type: "encryption",
            name: "Military-Grade Encryption",
            description: "All data must use military-grade encryption",
            value: "AES-256-GCM",
            isActive: true,
          },
        ],
        category: "compliance",
        severity: "high",
        enforcementType: "automatic",
        createdAt: "2024-01-05T13:00:00Z",
      },
    ],
    contractTemplates: [
      {
        id: "ec1",
        name: "Critical Infrastructure Contract",
        description: "Maximum security contract for critical energy infrastructure data",
        policyIds: ["ep1", "ep2", "ep3", "ep4"],
        policies: [],
        contractType: "multi_policy",
        status: "draft",
        createdAt: "2024-01-05T10:00:00Z",
        usageCount: 2,
      },
    ],
    externalOfferings: [],
    dataRequests: [],
  },
};

export function getDataForSpace(dataSpaceId: string) {
  return dataSpaceConfigs[dataSpaceId] || dataSpaceConfigs.healthcare;
}
